apiVersion: v2
name: testchart
description: very simple test chart
type: application
version: 0.2.6
home: https://github.com/300481/artifacthub2github
sources:
  - https://github.com/300481/artifacthub2github
maintainers:
  - name: "300481"
annotations:
  artifacthub.io/changes: |
    - "[change] testing repo-url."
